set -g base-index 1

unbind C-a
set-option -g prefix C-b
bind-key C-b send-prefix
set-option -ga terminal-overrides ",xterm-256color:Tc" 

set -g pane-border-style fg=blue
set -g pane-active-border-style fg=white
set -g status-style bg="#6746C5"

set-window-option -g automatic-rename on
set-option -g set-titles on

set -g status-keys vi 

setw -g mode-keys vi
setw -g monitor-activity on
setw -g mouse on

bind-key v split-window -h
bind-key s split-window -v

bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

# Use Alt-vim keys without prefix key to switch panes
bind -n C-M-h select-pane -L
bind -n C-M-j select-pane -D
bind -n C-M-k select-pane -U
bind -n C-M-l select-pane -R

# No delay for escape key press
set -sg escape-time 0

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

